### ISSUE TITLE
Update links & Repository in Docs

### ISSUE THREAD

**Issue by anthr76** [PurplShip/purplship-docs#1]
Hello,

I've been experimenting with the project lately. All seems well so far. Two issues to report.

Lot's of links point to https://doc.purplship.com/ instead of https://docs.purplship.com. On my side doc subdomain does not resolve to anything.

 It looks as though on commit https://github.com/PurplShip/purplship-docs/commit/a32ea78e6140dfc754adbd0757d49089846956fe the repository was changed to purplship-server from purplship. This has removed the documentation that used to exist. I would like to continuing integration. 

Thank you for all your contributions!

**Comment by DanH91** [comment]
Hello @anthr76,

I am more than glad to assist you.
Let's say that the project has undergone a massive cleanup lately and there have been a couple of breaking changes.

I am actively rewriting the documentation to reflect the new state of things.

In order to help you, I would be curious to know

- what version of `purplship` are you using?
- Are you using PurplShip as a python library or purplship-server?


All the previously existing documentation will be ported to https://docs.purplship.com I publish it back as soon as possible.

Please answer the question above that I may prioritize what would help you continue with your integration.

**Comment by anthr76** [comment]
I am currently using purplship as a python library. Version `2019.4.0`. I took a quick peek at Purplship server and would be happy to give it a try as well. I really appreciate the quick response! This project looks great!

**Comment by DanH91** [comment]
Thank you. I quickly spin back the 2019.4.0 documentation under https://archive.purplship.com

However, as I mentioned before they have been major improvements and changes in the new version 2020.4.0 but it is lacking documentation.

I am hoping to get them out progressively the upcoming days

**Comment by anthr76** [comment]
Great! I will keep an eye out for them. Thank you for your work.
